[versions]
# @keep
androidCompileSdk = "34"
androidGradlePlugin = "8.2.2"
# @keep
androidMinSdk = "24"
# @keep
androidTargetSdk = "34"
appcompat = "1.6.1"
activity = "1.8.2"
core-ktx = "1.12.0"
ktor = "2.3.8"
kotlinx-datetime = "0.5.0"
moko-mvvm = "0.16.1"
kamel = "0.9.3"
kermit = "2.0.3"
koin = "3.5.0"
koin-compose = "1.1.0"
kotlin = "1.9.22"
sql-delight = "1.5.5"
serialization = "1.6.3"
androidx-compose = "1.6.5"
androidx-compose-compiler = "1.5.11"

[libraries]
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx-compose-compiler" }
androidx-compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose" }

androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }
koin-compose-androidx = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kamel = { module = "media.kamel:kamel-image", version.ref = "kamel" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-loggin = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serilization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

moko-mvvm-core = { module = "dev.icerock.moko:mvvm-core", version.ref = "moko-mvvm" }
moko-mvvm-compose = { module = "dev.icerock.moko:mvvm-compose", version.ref = "moko-mvvm" }

sqldelight = { module = "com.squareup.sqldelight:runtime", version.ref = "sql-delight" }
sqldelight-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sql-delight" }
sqldelight-native = { module = "com.squareup.sqldelight:native-driver", version.ref = "sql-delight" }

[plugins]
sqldelight = { id = "com.squareup.sqldelight", version.ref = "sql-delight" }
kotlinNativeCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }